Repository staniel359/muffon, pull requests merged in 2024-01, with the labels that each got.

#138 Update Copyright year
  electron-builder.json
  src/pages/about/MainPage.vue
Labels: enhancement

#133 Fix for harmful switches that can be enabled via command line
  electron/helpers/data.js
  electron/helpers/utils.js
  electron/main.js
Labels: security

#143 Bitrate bug fix
  src/components/layout/panels/ThePlayerVariantsPanel/PlayerPanel/AudioSection/LeftControlsSection/BitrateSection.vue
Labels: Bug fix
