Repository staniel359/muffon, pull requests merged in 2025-02, with the labels that each got.

#231 Nuke eslint
  .npmrc
  biome.json
  electron/actions/views/setScale.js
  eslint.config.js
  package.json
  pnpm-lock.yaml
  src/components/containers/pages/artist/BaseArtistPageContainer.vue
  src/pages/radio/MainPage/ContentSection.vue
  vite.config.js
Labels: infrastructure, enhancement, optimization: speed

#212 Add Chinese translations
  electron/plugins/i18n.js
  electron/plugins/i18n/locales/zh.json
  src/helpers/data/locales.js
  src/plugins/dayjs.js
  src/plugins/i18n.js
  src/plugins/i18n/locales/zh.json
  src/plugins/i18nCountries.js
Labels: translation

#230 add flatpak args for better permissions
  electron-builder.json
Labels: enhancement, linux

#232 change copyright year
  electron-builder.json
  src/pages/about/MainPage.vue
Labels: enhancement

#233 Update dependencies & fix CI
  .github/workflows/main.yml
  package.json
  patches/app-builder-lib@26.0.7.patch
  patches/app-builder-lib@26.0.8.patch
  pnpm-lock.yaml
Labels: infrastructure, enhancement

#236 Fix builds
  .npmrc
  package.json
  pnpm-lock.yaml
Labels: infrastructure, bug fix, ci/cd
